IATA_MAP = {
    # ===== INDIA =====
    "lucknow": "LKO",
    "delhi": "DEL",
    "new delhi": "DEL",
    "mumbai": "BOM",
    "bombay": "BOM",
    "bangalore": "BLR",
    "bengaluru": "BLR",
    "chennai": "MAA",
    "madras": "MAA",
    "hyderabad": "HYD",
    "kolkata": "CCU",
    "calcutta": "CCU",
    "ahmedabad": "AMD",
    "pune": "PNQ",
    "goa": "GOI",
    "varanasi": "VNS",
    "jaipur": "JAI",
    "amritsar": "ATQ",
    "bhopal": "BHO",
    "indore": "IDR",
    "nagpur": "NAG",
    "patna": "PAT",
    "ranchi": "IXR",
    "bhubaneswar": "BBI",
    "guwahati": "GAU",
    "chandigarh": "IXC",
    "coimbatore": "CJB",
    "kochi": "COK",
    "cochin": "COK",
    "thiruvananthapuram": "TRV",
    "trivandrum": "TRV",
    "visakhapatnam": "VTZ",
    "vizag": "VTZ",
    "mangalore": "IXE",
    "srinagar": "SXR",
    "jammu": "IXJ",
    "leh": "IXL",
    "dehradun": "DED",
    "raipur": "RPR",
    "agra": "AGR",
    "aurangabad": "IXU",
    "udaipur": "UDR",
    "jodhpur": "JDH",
    "madurai": "IXM",
    "tiruchirappalli": "TRZ",
    "trichy": "TRZ",
    "vijayawada": "VGA",
    "hubli": "HBX",
    "bagdogra": "IXB",
    "dibrugarh": "DIB",
    "imphal": "IMF",
    "port blair": "IXZ",
    "shirdi": "SAG",
    "tirupati": "TIR",

    # ===== UNITED STATES =====
    "new york": "JFK",
    "new york city": "JFK",
    "nyc": "JFK",
    "los angeles": "LAX",
    "la": "LAX",
    "chicago": "ORD",
    "houston": "IAH",
    "dallas": "DFW",
    "miami": "MIA",
    "atlanta": "ATL",
    "san francisco": "SFO",
    "seattle": "SEA",
    "boston": "BOS",
    "denver": "DEN",
    "las vegas": "LAS",
    "phoenix": "PHX",
    "washington": "IAD",
    "washington dc": "IAD",
    "orlando": "MCO",
    "minneapolis": "MSP",
    "detroit": "DTW",
    "philadelphia": "PHL",
    "charlotte": "CLT",
    "salt lake city": "SLC",
    "portland": "PDX",
    "san diego": "SAN",
    "baltimore": "BWI",
    "tampa": "TPA",
    "austin": "AUS",
    "nashville": "BNA",
    "new orleans": "MSY",
    "kansas city": "MCI",
    "cleveland": "CLE",
    "pittsburgh": "PIT",
    "raleigh": "RDU",
    "indianapolis": "IND",
    "columbus": "CMH",
    "san jose": "SJC",
    "oakland": "OAK",
    "honolulu": "HNL",
    "anchorage": "ANC",
    "memphis": "MEM",
    "st louis": "STL",
    "cincinnati": "CVG",
    "milwaukee": "MKE",
    "buffalo": "BUF",
    "richmond": "RIC",
    "jacksonville": "JAX",
    "sacramento": "SMF",
    "albuquerque": "ABQ",
    "tucson": "TUS",
    "el paso": "ELP",

    # ===== UNITED KINGDOM =====
    "london": "LHR",
    "manchester": "MAN",
    "birmingham": "BHX",
    "edinburgh": "EDI",
    "glasgow": "GLA",
    "bristol": "BRS",
    "leeds": "LBA",
    "newcastle": "NCL",
    "belfast": "BFS",
    "cardiff": "CWL",
    "liverpool": "LPL",
    "southampton": "SOU",
    "aberdeen": "ABZ",
    "inverness": "INV",
    "exeter": "EXT",
    "norwich": "NWI",
    "nottingham": "EMA",

    # ===== EUROPE =====
    # France
    "paris": "CDG",
    "nice": "NCE",
    "lyon": "LYS",
    "marseille": "MRS",
    "bordeaux": "BOD",
    "toulouse": "TLS",
    "strasbourg": "SXB",
    "nantes": "NTE",
    # Germany
    "frankfurt": "FRA",
    "munich": "MUC",
    "berlin": "BER",
    "hamburg": "HAM",
    "dusseldorf": "DUS",
    "cologne": "CGN",
    "stuttgart": "STR",
    "hannover": "HAJ",
    "nuremberg": "NUE",
    "dresden": "DRS",
    # Spain
    "madrid": "MAD",
    "barcelona": "BCN",
    "malaga": "AGP",
    "palma": "PMI",
    "valencia": "VLC",
    "seville": "SVQ",
    "bilbao": "BIO",
    "ibiza": "IBZ",
    "tenerife": "TFS",
    "gran canaria": "LPA",
    # Italy
    "rome": "FCO",
    "milan": "MXP",
    "venice": "VCE",
    "florence": "FLR",
    "naples": "NAP",
    "bologna": "BLQ",
    "catania": "CTA",
    "palermo": "PMO",
    "turin": "TRN",
    "bari": "BRI",
    # Netherlands
    "amsterdam": "AMS",
    "rotterdam": "RTM",
    "eindhoven": "EIN",
    # Belgium
    "brussels": "BRU",
    "liege": "LGG",
    # Switzerland
    "zurich": "ZRH",
    "geneva": "GVA",
    "basel": "BSL",
    # Austria
    "vienna": "VIE",
    "salzburg": "SZG",
    "innsbruck": "INN",
    # Portugal
    "lisbon": "LIS",
    "porto": "OPO",
    "faro": "FAO",
    # Greece
    "athens": "ATH",
    "thessaloniki": "SKG",
    "heraklion": "HER",
    "rhodes": "RHO",
    "corfu": "CFU",
    "mykonos": "JMK",
    "santorini": "JTR",
    # Scandinavia
    "stockholm": "ARN",
    "oslo": "OSL",
    "copenhagen": "CPH",
    "helsinki": "HEL",
    "reykjavik": "KEF",
    "gothenburg": "GOT",
    "bergen": "BGO",
    # Eastern Europe
    "warsaw": "WAW",
    "krakow": "KRK",
    "prague": "PRG",
    "budapest": "BUD",
    "bucharest": "OTP",
    "sofia": "SOF",
    "zagreb": "ZAG",
    "ljubljana": "LJU",
    "bratislava": "BTS",
    "riga": "RIX",
    "tallinn": "TLL",
    "vilnius": "VNO",
    "kiev": "KBP",
    "kyiv": "KBP",
    "minsk": "MSQ",
    "chisinau": "KIV",
    "tirana": "TIA",
    "skopje": "SKP",
    "sarajevo": "SJJ",
    "belgrade": "BEG",
    "podgorica": "TGD",
    # Russia
    "moscow": "SVO",
    "st petersburg": "LED",
    "saint petersburg": "LED",
    "novosibirsk": "OVB",
    "yekaterinburg": "SVX",
    "kazan": "KZN",
    "sochi": "AER",
    # Turkey
    "istanbul": "IST",
    "ankara": "ESB",
    "izmir": "ADB",
    "antalya": "AYT",
    "bodrum": "BJV",
    "dalaman": "DLM",

    # ===== MIDDLE EAST =====
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "sharjah": "SHJ",
    "doha": "DOH",
    "riyadh": "RUH",
    "jeddah": "JED",
    "medina": "MED",
    "dammam": "DMM",
    "kuwait": "KWI",
    "kuwait city": "KWI",
    "muscat": "MCT",
    "bahrain": "BAH",
    "manama": "BAH",
    "amman": "AMM",
    "beirut": "BEY",
    "tel aviv": "TLV",
    "jerusalem": "TLV",
    "tehran": "IKA",
    "baghdad": "BGW",
    "erbil": "EBL",

    # ===== ASIA =====
    # China
    "beijing": "PEK",
    "shanghai": "PVG",
    "guangzhou": "CAN",
    "shenzhen": "SZX",
    "chengdu": "CTU",
    "chongqing": "CKG",
    "hangzhou": "HGH",
    "wuhan": "WUH",
    "xian": "XIY",
    "kunming": "KMG",
    "nanjing": "NKG",
    "tianjin": "TSN",
    "qingdao": "TAO",
    "xiamen": "XMN",
    "sanya": "SYX",
    "harbin": "HRB",
    "urumqi": "URC",
    "lhasa": "LXA",
    "hong kong": "HKG",
    "macau": "MFM",
    # Japan
    "tokyo": "NRT",
    "osaka": "KIX",
    "nagoya": "NGO",
    "sapporo": "CTS",
    "fukuoka": "FUK",
    "okinawa": "OKA",
    "hiroshima": "HIJ",
    "sendai": "SDJ",
    # South Korea
    "seoul": "ICN",
    "busan": "PUS",
    "jeju": "CJU",
    "daegu": "TAE",
    # Southeast Asia
    "singapore": "SIN",
    "kuala lumpur": "KUL",
    "bangkok": "BKK",
    "jakarta": "CGK",
    "bali": "DPS",
    "denpasar": "DPS",
    "manila": "MNL",
    "ho chi minh city": "SGN",
    "saigon": "SGN",
    "hanoi": "HAN",
    "phnom penh": "PNH",
    "vientiane": "VTE",
    "yangon": "RGN",
    "rangoon": "RGN",
    "naypyidaw": "NYT",
    "colombo": "CMB",
    "dhaka": "DAC",
    "kathmandu": "KTM",
    "phuket": "HKT",
    "chiang mai": "CNX",
    "penang": "PEN",
    "langkawi": "LGK",
    "lombok": "LOP",
    "surabaya": "SUB",
    "medan": "KNO",
    "cebu": "CEB",
    "davao": "DVO",
    "da nang": "DAD",
    # South Asia
    "karachi": "KHI",
    "lahore": "LHE",
    "islamabad": "ISB",
    "peshawar": "PEW",
    "quetta": "UET",
    "kabul": "KBL",
    "male": "MLE",
    "maldives": "MLE",
    # Central Asia
    "almaty": "ALA",
    "nur sultan": "NQZ",
    "astana": "NQZ",
    "tashkent": "TAS",
    "bishkek": "FRU",
    "dushanbe": "DYU",
    "ashgabat": "ASB",
    "baku": "GYD",
    "yerevan": "EVN",
    "tbilisi": "TBS",

    # ===== AFRICA =====
    # North Africa
    "cairo": "CAI",
    "alexandria": "HBE",
    "casablanca": "CMN",
    "marrakech": "RAK",
    "tunis": "TUN",
    "algiers": "ALG",
    "tripoli": "TIP",
    "luxor": "LXR",
    "hurghada": "HRG",
    "sharm el sheikh": "SSH",
    # East Africa
    "nairobi": "NBO",
    "addis ababa": "ADD",
    "dar es salaam": "DAR",
    "entebbe": "EBB",
    "kampala": "EBB",
    "kigali": "KGL",
    "djibouti": "JIB",
    "mogadishu": "MGQ",
    "zanzibar": "ZNZ",
    "kilimanjaro": "JRO",
    # West Africa
    "lagos": "LOS",
    "abuja": "ABV",
    "accra": "ACC",
    "dakar": "DKR",
    "abidjan": "ABJ",
    "conakry": "CKY",
    "freetown": "FNA",
    "monrovia": "ROB",
    "bamako": "BKO",
    "ouagadougou": "OUA",
    "lome": "LFW",
    "cotonou": "COO",
    # Southern Africa
    "johannesburg": "JNB",
    "cape town": "CPT",
    "durban": "DUR",
    "harare": "HRE",
    "lusaka": "LUN",
    "gaborone": "GBE",
    "windhoek": "WDH",
    "maputo": "MPM",
    "antananarivo": "TNR",
    "mauritius": "MRU",
    "port louis": "MRU",
    "reunion": "RUN",
    # Central Africa
    "kinshasa": "FIH",
    "brazzaville": "BZV",
    "libreville": "LBV",
    "yaounde": "YAO",
    "douala": "DLA",
    "bangui": "BGF",
    "ndjamena": "NDJ",
    "luanda": "LAD",

    # ===== NORTH AMERICA =====
    # Canada
    "toronto": "YYZ",
    "vancouver": "YVR",
    "montreal": "YUL",
    "calgary": "YYC",
    "edmonton": "YEG",
    "ottawa": "YOW",
    "winnipeg": "YWG",
    "halifax": "YHZ",
    "quebec city": "YQB",
    "victoria": "YYJ",
    # Mexico
    "mexico city": "MEX",
    "cancun": "CUN",
    "guadalajara": "GDL",
    "monterrey": "MTY",
    "tijuana": "TIJ",
    "los cabos": "SJD",
    "puerto vallarta": "PVR",
    "merida": "MID",
    "oaxaca": "OAX",
    # Caribbean
    "havana": "HAV",
    "kingston": "KIN",
    "nassau": "NAS",
    "santo domingo": "SDQ",
    "san juan": "SJU",
    "port of spain": "POS",
    "bridgetown": "BGI",
    "kingstown": "SVD",
    "castries": "SLU",
    "roseau": "DOM",
    # Central America
    "panama city": "PTY",
    "san jose": "SJO",
    "guatemala city": "GUA",
    "tegucigalpa": "TGU",
    "managua": "MGA",
    "san salvador": "SAL",
    "belize city": "BZE",

    # ===== SOUTH AMERICA =====
    "sao paulo": "GRU",
    "rio de janeiro": "GIG",
    "brasilia": "BSB",
    "buenos aires": "EZE",
    "bogota": "BOG",
    "lima": "LIM",
    "santiago": "SCL",
    "caracas": "CCS",
    "quito": "UIO",
    "guayaquil": "GYE",
    "medellin": "MDE",
    "cartagena": "CTG",
    "montevideo": "MVD",
    "asuncion": "ASU",
    "la paz": "LPB",
    "santa cruz": "VVI",
    "cusco": "CUZ",
    "manaus": "MAO",
    "recife": "REC",
    "fortaleza": "FOR",
    "belo horizonte": "CNF",
    "porto alegre": "POA",
    "salvador": "SSA",
    "cayenne": "CAY",
    "paramaribo": "PBM",
    "georgetown": "GEO",

    # ===== OCEANIA =====
    # Australia
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
    "perth": "PER",
    "adelaide": "ADL",
    "gold coast": "OOL",
    "cairns": "CNS",
    "darwin": "DRW",
    "canberra": "CBR",
    "hobart": "HBA",
    "alice springs": "ASP",
    # New Zealand
    "auckland": "AKL",
    "wellington": "WLG",
    "christchurch": "CHC",
    "queenstown": "ZQN",
    "dunedin": "DUD",
    # Pacific Islands
    "fiji": "NAN",
    "nadi": "NAN",
    "suva": "SUV",
    "port moresby": "POM",
    "honiara": "HIR",
    "port vila": "VLI",
    "noumea": "NOU",
    "papeete": "PPT",
    "apia": "APW",
    "nuku alofa": "TBU",
    "funafuti": "FUN",
    "tarawa": "TRW",
    "majuro": "MAJ",
    "koror": "ROR",
    "pohnpei": "PNI",
    "guam": "GUM",
    "saipan": "SPN",
}